
[general]
host = "0.0.0.0"
port = 6432
admin_username = "admin_user"
admin_password = ""
admin_auth_type = "ldap"
admin_auth_ldapurl = "ldap://127.0.0.1:3893"
admin_auth_ldapsuffix  = "@example.com"

[pools.sharded_db.users.0]
username = "sharding_user"
password = "sharding_user"
auth_type = "ldap"
auth_ldapurl = "ldap://127.0.0.1:3893"
auth_ldapsuffix  = "@example.com"
pool_size = 10
min_pool_size = 1
pool_mode = "transaction"

[pools.sharded_db.shards.0]
servers = [
  [ "127.0.0.1", 5432, "primary" ],
]
database = "shard0"
